### ISSUE TITLE
now the game crash when i log in my account

### ISSUE THREAD

**Issue by Numder02** [hq-af/hqOsu#44]
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at #=zWgj4z8JqriNW_u43vIdQfYs=.#=zY4OmngXusSMR(String #=z9bBrhJQ=)
   at #=z70rm5KPPAzZnepoi5i8TN94=.#=z6H$ldKw=(#=zwL6sbs_c$8m4r531cA== #=z$gnV$JQ=)
   at #=z70rm5KPPAzZnepoi5i8TN94=..ctor(String #=znPK6Bos=, Boolean #=zoMK1Fj0=)
   at #=zglRjBYvSXqJC429__HkHySjfOm5_.#=zoUnqANyPuhWd()
   at #=zglRjBYvSXqJC429__HkHySjfOm5_.#=zlYnbnRYpg2XJroIgcQ==(Object #=zhYq7J44=, KeyEventArgs #=zcUVBobw=)
   at System.Windows.Forms.KeyEventHandler.Invoke(Object sender, KeyEventArgs e)
   at #=zPWu4DuNkSwTZqk8TKQ==.#=zv52qtogS4UJV(Object #=zhYq7J44=, KeyEventArgs #=zcUVBobw=)
   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at dje_zF8U7AWN7QQF9KX8GL7X6WFLGX8XA_ejd.WndProc(Message& #=zYdeTdN8=)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Numder02** [comment]
miss it i fixed it

**Comment by isiahah** [comment]
> miss it i fixed it

how did you fix it?

**Comment by hq-af** [comment]
fixed, restart hqosu
