### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by hchan69** [hq-af/hqOsu#53]
i was playing then suddenly my osu! crashed
and this happens
`Unhandled Exception: System.FormatException: Input string was not in a correct format.
at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
at System.Number.ParseInt32(String s, Numberstyles style, NumberFormatInfo info)
at ??????????????????????????????????????????????????????????????.????????????????????????????????????????????????????(Boolean )
at hqOsu.Hax.Gate.OwOAG5FHVLDDJHVBV75P099GRFS()
at #=qH085IMd8ewY1faJNsIWBcrkidEhFpRiHcgl$q$h35Dw=.#=zhtHqoZ4=()`

**Comment by hchan69** [comment]
this always happen whenever i change something on config.ini
