### ISSUE TITLE
?

### ISSUE THREAD

**Issue by egenisvegan** [hq-af/hqOsu#56]
Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'C:\Users\car\Desktop\osu!\osu!.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at hqOsu.Loader.Loader.LoadPatch(String patchPath)
   at hqOsu.Loader.Loader.Main()

**Comment by Numder02** [comment]
First: You cannot open two hqOsu at the same time. Second: try disabling your antivirus.
