### ISSUE TITLE
What's this

### ISSUE THREAD

**Issue by denmarkistrash** [hq-af/hqOsu#57]
Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at ?????????????????????????????????????????.?????????????????????????????????????????(String , Double )
   at ?????????????????????????????????????????.?????????????????????????????????????????(Boolean )
   at hqOsu.Hax.Gate.OwOAG5FHVLDDJHVBV75P099GRFS()
   at #=qH085IMd8ewY1faJNsIWBcrkidEhFpRiHcgl$q$h3SDw=.#=zhtHqoZ4=()

**Comment by ProgrammingCatss** [comment]
im getting that too
